-- Generated by scripts/build/compose-master-migrations.mjs.
-- Additive parity migration for the authoritative master project only:
-- bxtcuhkotumitoqtrcej / schema mazer.
-- It deliberately fails closed when the pre-existing master tables are absent.

do $preflight$
begin
  if to_regnamespace('mazer') is null then
    raise exception 'MAZER_MASTER_SCHEMA_MISSING';
  end if;

  if to_regclass('mazer.mazer_profiles') is null
    or to_regclass('mazer.mazer_progression_states') is null
    or to_regclass('mazer.mazer_ai_progression_states') is null
    or to_regclass('mazer.mazer_cycle_receipts') is null
  then
    raise exception 'MAZER_MASTER_TABLES_INCOMPLETE';
  end if;
end;
$preflight$;

alter table mazer.mazer_progression_states
  add column if not exists revision bigint not null default 0 check (revision >= 0);

alter table mazer.mazer_profiles
  add column if not exists revision bigint not null default 0 check (revision >= 0);

comment on column mazer.mazer_progression_states.revision is
  'Monotonic optimistic-concurrency revision. Authenticated clients must compare before replacing canonical account progression.';

comment on column mazer.mazer_profiles.revision is
  'Monotonic optimistic-concurrency revision for player-facing settings synced across devices.';

alter table mazer.mazer_profiles
  add column if not exists username text
    check (username is null or (char_length(username) between 2 and 15 and username ~ '^[a-zA-Z0-9._-]+$'));

comment on column mazer.mazer_profiles.username is
  'Player-chosen unique display handle. Optional -- null until the player sets one. Case-insensitively unique via mazer_profiles_username_unique_idx, the actual source of truth for the uniqueness guarantee (not the availability-check RPC below, which is a best-effort UX nicety only).';

-- Case-insensitive uniqueness, enforced atomically at the database level so
-- two clients racing to claim the same name can never both succeed --
-- unlike a check-then-write pattern in application code.
create unique index if not exists mazer_profiles_username_unique_idx
  on mazer.mazer_profiles (lower(username))
  where username is not null;

-- RLS on mazer_profiles restricts reads to a user's own row (see
-- 20260709011209_mazer_account_storage_contracts.sql), so there is no way
-- for a client to check whether another user already holds a given
-- username. This function runs as its definer (bypassing RLS internally)
-- but only ever returns a boolean, never another user's actual profile
-- data -- safe to expose to any authenticated caller. It is a UX
-- convenience for instant "taken/available" feedback while typing; the
-- unique index above is what actually prevents a collision at save time.
create or replace function mazer.mazer_is_username_available(candidate text)
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select not exists (
    select 1 from mazer.mazer_profiles
    where lower(username) = lower(candidate)
  );
$$;

revoke all on function mazer.mazer_is_username_available(text) from public;
grant execute on function mazer.mazer_is_username_available(text) to authenticated;

-- 1. Replace both 1-99 completion-ordinal ceilings with lower-bound-only
-- checks. Player and AI remain separate tracks, but both advance +1 for each
-- accepted completion and neither has an application-level ceiling.
alter table mazer.mazer_progression_states
  alter column player_level type bigint,
  alter column player_completed_cycles type bigint;

alter table mazer.mazer_progression_states
  drop constraint if exists mazer_progression_states_player_level_check;
alter table mazer.mazer_progression_states
  add constraint mazer_progression_states_player_level_check
    check (player_level >= 1);

-- The completion ordinal is unbounded, but the separate difficulty pressure
-- remains in the same client-owned 8..400 envelope. Widen the legacy 1..240
-- constraints before the completion RPC starts advancing this field by the
-- canonical +4 step.
alter table mazer.mazer_progression_states
  drop constraint if exists mazer_progression_states_player_target_complexity_check;
alter table mazer.mazer_progression_states
  add constraint mazer_progression_states_player_target_complexity_check
    check (player_target_complexity between 8 and 400);

alter table mazer.mazer_ai_progression_states
  alter column level type bigint,
  alter column completed_cycles type bigint;

alter table mazer.mazer_ai_progression_states
  drop constraint if exists mazer_ai_progression_states_level_check;
alter table mazer.mazer_ai_progression_states
  add constraint mazer_ai_progression_states_level_check
    check (level >= 1);

alter table mazer.mazer_ai_progression_states
  drop constraint if exists mazer_ai_progression_states_target_complexity_check;
alter table mazer.mazer_ai_progression_states
  add constraint mazer_ai_progression_states_target_complexity_check
    check (target_complexity between 8 and 400);

-- 2. Leaderboard tie-breaking needs a timestamp of when the current level
-- was actually reached (existing rows have no trustworthy equivalent --
-- last_completed_cycle_at reflects the most recent finished cycle, not
-- specifically a level-up event, so it is not reused here). Nullable and
-- unbacfilled for existing rows: a leaderboard ordering by this column
-- should fall back to a stable secondary key (e.g. user id) for rows where
-- it is null, rather than this migration guessing a backfill value it has
-- no real evidence for.
alter table mazer.mazer_progression_states
  add column if not exists level_reached_at timestamp with time zone;

comment on column mazer.mazer_progression_states.level_reached_at is
  'When player_level last advanced. Null for rows that predate this column -- leaderboard ordering must handle that, not assume every row has one.';

-- 3. Cycle receipts gain optional recipe provenance so a future completion
-- RPC can verify what a client claims it completed without a second
-- ledger. All three are nullable: existing receipts and any receipt from
-- before the endless ruleset exists legitimately have none of this.
alter table mazer.mazer_cycle_receipts
  add column if not exists ruleset_id text,
  add column if not exists recipe_version integer,
  add column if not exists recipe_hash text;

alter table mazer.mazer_cycle_receipts
  drop constraint if exists mazer_cycle_receipts_ruleset_id_check;
alter table mazer.mazer_cycle_receipts
  add constraint mazer_cycle_receipts_ruleset_id_check
    check (ruleset_id is null or ruleset_id in ('legacy-v1', 'endless-v1'));

comment on column mazer.mazer_cycle_receipts.ruleset_id is
  'Which progression ruleset generated the completed level -- legacy-v1 (levels 1-99, complexity-derived) or endless-v1 (levels 100+, recipe-derived). Null for receipts recorded before this column existed.';
comment on column mazer.mazer_cycle_receipts.recipe_version is
  'Recipe schema version the completed endless-v1 level was resolved under. Null for legacy-v1 receipts and any receipt predating this column.';
comment on column mazer.mazer_cycle_receipts.recipe_hash is
  'Opaque hash of the resolved recipe the client claims it completed, for future server-side verification against a re-resolved recipe. Null until a completion path actually populates it.';

-- 4. A stable idempotency key for receipts, so a future completion RPC can
-- reject a duplicate submission (retried request, replayed client state)
-- without double-advancing progression. Nullable/unbacfilled for existing
-- receipts -- retroactively minting one would be a guess, not evidence.
alter table mazer.mazer_cycle_receipts
  add column if not exists client_run_id uuid;

-- Scope idempotency to one account. A caller must not be able to reserve a
-- globally-known UUID and block another account's otherwise valid receipt.
drop index if exists mazer.mazer_cycle_receipts_client_run_id_unique_idx;
create unique index if not exists mazer_cycle_receipts_user_client_run_id_unique_idx
  on mazer.mazer_cycle_receipts (user_id, client_run_id)
  where client_run_id is not null;

comment on column mazer.mazer_cycle_receipts.client_run_id is
  'Client-generated idempotency key for one play/menu-demo attempt. Null for receipts recorded before this column existed. New completion RPC calls require it and enforce uniqueness per account.';

alter table mazer.mazer_profiles enable row level security;
alter table mazer.mazer_profiles force row level security;
alter table mazer.mazer_progression_states enable row level security;
alter table mazer.mazer_progression_states force row level security;
alter table mazer.mazer_ai_progression_states enable row level security;
alter table mazer.mazer_ai_progression_states force row level security;
alter table mazer.mazer_cycle_receipts enable row level security;
alter table mazer.mazer_cycle_receipts force row level security;

alter function mazer.mazer_is_username_available(text) owner to postgres;
revoke all on function mazer.mazer_is_username_available(text) from public, anon, service_role;
grant execute on function mazer.mazer_is_username_available(text) to authenticated;
