import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, test } from 'vitest';

const readRepoFile = (path: string): string => readFileSync(resolve(process.cwd(), path), 'utf8');

const extractCurrentMarker = (markerDoc: string): number => {
  const match = markerDoc.match(/Current marker:\s*`(\d+)%`/);
  expect(match, 'marker doc must publish a current marker').not.toBeNull();
  return Number(match?.[1]);
};

const extractRetiredMarker = (markerDoc: string): number => {
  const match = markerDoc.match(/Retired marker:\s*`(\d+)%`/);
  expect(match, 'retired marker doc must publish a retired marker').not.toBeNull();
  return Number(match?.[1]);
};

const extractCurrentTotal = (markerDoc: string): number => {
  const match = markerDoc.match(/-\s*`(\d+)\s*\/\s*100`/);
  expect(match, 'marker doc must publish a current total').not.toBeNull();
  return Number(match?.[1]);
};

const extractWeightedTablePoints = (markerDoc: string): number[] => markerDoc
  .split('\n')
  .filter((line) => line.startsWith('| ') && !line.startsWith('| Segment') && !line.startsWith('| ---'))
  .map((line) => line.split('|').map((cell) => cell.trim()))
  .filter((cells) => cells.length >= 4)
  .map((cells) => {
    const pointsMatch = cells[3]?.match(/^`(\d+)`$/);
    expect(pointsMatch, `marker row must have numeric current points: ${cells[1]}`).not.toBeNull();
    return Number(pointsMatch?.[1]);
  });

describe('Mazer completion markers', () => {
  test('keeps the active mechanics/mobile marker arithmetic and current truth synchronized', () => {
    const markerDoc = readRepoFile('docs/research/MAZER_MECHANICS_MOBILE_COMPLETION_MARKER.md');
    const currentTruth = readRepoFile('docs/current-truth.md');
    const agentRules = readRepoFile('AGENTS.md');

    const currentMarker = extractCurrentMarker(markerDoc);
    const currentTotal = extractCurrentTotal(markerDoc);
    const weightedPoints = extractWeightedTablePoints(markerDoc);

    expect(weightedPoints.reduce((sum, points) => sum + points, 0)).toBe(currentTotal);
    expect(currentTotal).toBe(currentMarker);
    expect(currentTruth).toContain(`- \`${currentMarker}%\``);
    expect(markerDoc).toContain('This is the active completion marker for the current Mazer direction.');
    expect(markerDoc).toContain('Do not ratchet the retired legacy visual 1:1 marker from this lane.');
    expect(currentTruth).toContain('legacy visual 1:1 marker is retired');
    expect(currentTruth).toContain('bounded extreme scale-`149` smoke');
    expect(markerDoc).toContain('`99% -> 100%`');
    expect(markerDoc).toContain('scale-`149`');
    expect(agentRules).toContain('use `docs/research/MAZER_MECHANICS_MOBILE_COMPLETION_MARKER.md` as the active percent marker');
  });

  test('keeps the active proof spine explicit and aligned with repo verify scripts', () => {
    const currentTruth = readRepoFile('docs/current-truth.md');
    const systemMap = readRepoFile('docs/system-map.md');
    const packageJson = readRepoFile('package.json');
    const verifyScript = readRepoFile('scripts/verify/run-verify.mjs');

    expect(packageJson).toContain('"verify": "node ./scripts/verify/run-verify.mjs"');
    expect(packageJson).toContain('"test:verify": "vitest run tests/reset tests/ai/demo-walker.test.ts tests/scenes/menu-render-frame.test.ts tests/analysis/maze-cycle-telemetry-report.test.mjs --maxWorkers 1"');
    expect(verifyScript).toContain("runNpm(['run', 'test:verify'])");
    expect(verifyScript).toContain("runNpm(['run', 'build'])");
    expect(currentTruth).toContain('Current `verify` means:');
    expect(currentTruth).toContain('- `npm run test:verify`');
    expect(currentTruth).toContain('- `npm run build`');
    expect(currentTruth).toContain('Current `test:verify` means:');
    expect(currentTruth).toContain('- `tests/reset`');
    expect(currentTruth).toContain('- `tests/ai/demo-walker.test.ts`');
    expect(currentTruth).toContain('- `tests/scenes/menu-render-frame.test.ts`');
    expect(currentTruth).toContain('- `tests/analysis/maze-cycle-telemetry-report.test.mjs`');
    expect(currentTruth).toContain('- `--maxWorkers 1`');
    expect(currentTruth).toContain('npm run lint');
    expect(systemMap).toContain('docs/research/MAZER_MECHANICS_MOBILE_COMPLETION_MARKER.md');
    expect(systemMap).toContain('docs/current-truth.md');
    expect(systemMap).toContain('- `npm run test:verify`');
    expect(systemMap).toContain('- `npm run build`');
    expect(systemMap).toContain('- `tests/reset`');
    expect(systemMap).toContain('- `tests/ai/demo-walker.test.ts`');
    expect(systemMap).toContain('- `tests/scenes/menu-render-frame.test.ts`');
    expect(systemMap).toContain('- `tests/analysis/maze-cycle-telemetry-report.test.mjs`');
    expect(systemMap).toContain('- `--maxWorkers 1`');
    expect(systemMap).toContain('scale-`149` smoke');
  });

  test('keeps the level/rank/complexity progression contract tracked', () => {
    const markerDoc = readRepoFile('docs/research/MAZER_AUTH_AI_VISUAL_COMPLETION_MARKER.md');
    const contractDoc = readRepoFile('docs/research/MAZER_LEVEL_RANK_COMPLEXITY_CONTRACT.md');

    expect(markerDoc).toContain('| Player-facing auth gate | 94% |');
    expect(markerDoc).toContain('fitness-app persistent-login pattern');
    expect(markerDoc).toContain('remembered identity is now a JSON state');
    expect(markerDoc).toContain('sign-out is local-only');
    expect(markerDoc).toContain('| Account-scoped settings persistence | 70% |');
    expect(markerDoc).toContain('resolveLegacyGameToggleStorage()` scopes `mazer.game-toggles.v1`');
    expect(markerDoc).toContain('guest and signed-in account settings do not bleed into the raw global key or each other');
    expect(markerDoc).toContain('bounded migration for older unscoped `mazer.game-toggles.v1` preferences');
    expect(markerDoc).toContain('existing scoped preferences are never overwritten');
    expect(markerDoc).toContain('Account-scoped toggle migration proof');
    expect(markerDoc).toContain('| Player input and movement correctness | 52% |');
    expect(markerDoc).toContain('route through `tryMovePlayerFromInput()`');
    expect(markerDoc).toContain('one visible move');
    expect(markerDoc).toContain('| Auth QA and production readiness | 94% |');
    expect(markerDoc).toContain('token-free remembered identity storage');
    expect(markerDoc).toContain('Runtime diagnostics now expose a safe auth proof block');
    expect(markerDoc).toContain('Runtime auth diagnostics proof');
    expect(markerDoc).toContain('Runtime auth browser proof');
    expect(markerDoc).toContain('auth.rememberedIdentity.sessionState = "ready"');
    expect(markerDoc).toContain('| Level/rank/complexity contract | 72% |');
    expect(markerDoc).toContain('| Procedural difficulty generator shaping | 61% |');
    expect(markerDoc).toContain('Runtime diagnostics now expose `generationReview`');
    expect(markerDoc).toContain('`under-target`, `on-target`, or `over-target` delivery classification');
    expect(markerDoc).toContain('bounded target-based seed selection');
    expect(markerDoc).toContain('closest available candidate instead of blindly accepting the first seed');
    expect(markerDoc).toContain('high/mythic targets can evaluate up to nine seeds');
    expect(markerDoc).toContain('selection-window miss diagnostics');
    expect(markerDoc).toContain('`allCandidatesUnderTarget` / `allCandidatesOverTarget` flags');
    expect(markerDoc).toContain('retry ladder now has two bounded steps');
    expect(markerDoc).toContain('`pressureRetryUsed`');
    expect(markerDoc).toContain('`adaptiveRetryUsed`');
    expect(markerDoc).toContain('`adaptiveRetryCandidateCount`');
    expect(markerDoc).toContain('`adaptiveRetryScale`');
    expect(markerDoc).toContain('Atlas-safe cycle telemetry reports now include normalized generation delivery/retry review');
    expect(markerDoc).toContain('calibrate branch/fill/dead-end shaping against retry misses');
    expect(markerDoc).toContain('| Mobile shell, portrait lock, and device harness | 24% |');
    expect(markerDoc).toContain('Screen Orientation API can only be best-effort');
    expect(markerDoc).toContain('true hard portrait lock requires a native/PWA install context or mobile shell decision');
    expect(markerDoc).toContain('fails if active text labels leave the viewport');
    expect(markerDoc).toContain('tmp/captures/mazer-mobile-auth-options-layout-review.png');
    expect(markerDoc).toContain('tmp/captures/mazer-mobile-options-scroll-rail-proof-rebuilt.png');
    expect(markerDoc).toContain('tmp/captures/mazer-mobile-pause-scroll-rail-proof-rebuilt.png');
    expect(markerDoc).toContain('asserts scroll viewport/track/thumb affordance diagnostics');
    expect(markerDoc).toContain('tmp/captures/mazer-ui-surfaces/2026-07-10T06-28-31-086Z/summary.json');
    expect(markerDoc).toContain('tmp/captures/mazer-mobile-auth-options-scroll-affordance-next-pass.png');
    expect(markerDoc).toContain('Played-game phone HUD proof now reserves a top lane');
    expect(markerDoc).toContain('| Visual defaults and menu controls | 85% |');
    expect(markerDoc).toContain('authenticated mobile Start/Options side-by-side on the bottom row');
    expect(markerDoc).toContain('the played-game skill badge is top-centered and clear of the maze');
    expect(markerDoc).toContain('full-height affordance when the current Options content fits without overflow');
    expect(markerDoc).toContain('30% move speed');
    expect(markerDoc).toContain('aligns the canonical fresh-session default contract');
    expect(markerDoc).toContain('| Player-facing Options info guide | 68% |');
    expect(markerDoc).toContain('Compass points to End');
    expect(markerDoc).toContain('the played-game pause overlay now renders `PLAYER GUIDE` before the controls');
    expect(markerDoc).toContain('visible `Game Toggles` section title has been removed');
    expect(markerDoc).toContain('`Skill Lvl` / `AI Skill Lvl` means rank plus level');
    expect(markerDoc).toContain('`Clock + Score` means current run time plus 0-100 run-quality score');
    expect(markerDoc).toContain('`Runs + Maze Lvl` means completed clears/cycles plus the measured current maze level');
    expect(markerDoc).toContain('now avoid the old compact `Lv` fallback');
    expect(markerDoc).toContain('Mobile Options now uses the same scroll viewport/rail contract as played-game Pause');
    expect(markerDoc).toContain('corrects the old misleading `AI marker + trail` guide copy to `player marker + trail`');
    expect(markerDoc).toContain('no active text bounds failures, no text overlaps');
    expect(markerDoc).toContain('`Maze Scale` and `Camera Scale` as hidden advanced controls');
    expect(markerDoc).toContain('| DiscordOS Mazer feedback board | 90% |');
    expect(markerDoc).toContain('| Visual proof verification discipline | 99% |');
    expect(markerDoc).toContain('played-game pause proof now expects the real player-facing `Reset` and `Menu` buttons');
    expect(markerDoc).toContain('rejects stale `Account`/`Resume`');
    expect(markerDoc).toContain('tmp/captures/mazer-ui-surfaces/2026-07-10T03-35-18-327Z/summary.json');
    expect(markerDoc).toContain('checks active native input bounds');
    expect(markerDoc).toContain('tmp/captures/mazer-ui-surfaces/2026-07-10T06-28-31-086Z/summary.json');
    expect(markerDoc).toContain('checks text-label overlap');
    expect(markerDoc).toContain('checks menu control spacing');
    expect(markerDoc).toContain('checks captured overlay scroll rail diagnostics');
    expect(markerDoc).toContain('waits for a fully readable title before taking the menu screenshot');
    expect(markerDoc).toContain('active `buttons[]` with text plus bounds');
    expect(markerDoc).toContain('clicks Login/Start/Options from those actual button hitboxes');
    expect(markerDoc).toContain('tmp/captures/mazer-ui-surfaces/2026-07-10T06-51-59-043Z/summary.json');
    expect(markerDoc).toContain('runtime-diagnostics auth fixture');
    expect(markerDoc).toContain('tmp/captures/mazer-ui-surfaces/2026-07-10T15-12-27-898Z/summary.json');
    expect(markerDoc).toContain('| AI/playbook progression contracts | 97% |');
    expect(markerDoc).toContain('removes the remaining visual-goal inference fallback');
    expect(markerDoc).toContain('wrapped compass-local pressure');
    expect(markerDoc).toContain('compass-trap regression');
    expect(markerDoc).toContain('no longer uses a cached solved-distance field');
    expect(markerDoc).toContain('fails if the visible memory target leaks an unseen end tile');
    expect(markerDoc).toContain('cannot expose the end tile before the AI is actually on it');
    expect(markerDoc).toContain('hides the goal tile as a memory retarget entirely');
    expect(markerDoc).toContain('active non-goal target tile changes material by thought state');
    expect(markerDoc).toContain('AI target tile is pinned yellow while thought state remains diagnostic-only');
    expect(markerDoc).toContain('monotonicAverageScorePass = true');
    expect(markerDoc).toContain('monotonicRouteEfficiencyPass = true');
    expect(markerDoc).toContain('score E/D/C/B/A/S = `59.417 / 61.6 / 61.6 / 61.6 / 61.6 / 61.6`');
    expect(markerDoc).toContain('richer high-rank distinction beyond the current D-grade floor');
    expect(markerDoc).toContain('Live AI target proof');
    expect(markerDoc).toContain('0` had `targetPoint == goal` before `playerAtGoal/reachedGoal`');
    expect(markerDoc).toContain('npm run live:menu-ai-qa');
    expect(markerDoc).toContain('menu-ai-target-next-pass.summary.json');
    expect(markerDoc).toContain('| Play-mode completion lifecycle | 76% |');
    expect(markerDoc).toContain('the play timer restarts at construction release instead of counting build time');
    expect(markerDoc).toContain('explicit `resolveLegacyPlayLifecycleSnapshot()` contract');
    expect(markerDoc).toContain('matching `play.lifecycle` / `runtime.playLifecycle` diagnostics');
    expect(markerDoc).toContain('mazer.cycle-learning.consumer.v1');
    expect(markerDoc).toContain('shortestViablePathLength');
    expect(markerDoc).toContain('routeOverrunRatio');
    expect(markerDoc).toContain('Fresh player-maze generation proof');
    expect(markerDoc).toContain('target complexity, completed cycles, level, and score');
    expect(markerDoc).toContain('first-pass numeric run-quality score');
    expect(markerDoc).toContain('Badge/timer/guide proof');
    expect(markerDoc).toContain('standalone played-game top timer panel was removed');
    expect(markerDoc).toContain('phone portrait pause moved to the top-right action lane');
    expect(markerDoc).toContain('route waste can now force `ease`');
    expect(markerDoc).toContain('Run-quality progression proof');
    expect(markerDoc).toContain('unsafe frame timing holds difficulty without punishing the player');
    expect(markerDoc).toContain('play input locks');
    expect(markerDoc).toContain('the handoff burst also renders in play mode');
    expect(markerDoc).toContain('a fresh `play-goal-reset` generation request is queued after the handoff');
    expect(markerDoc).toContain('the player marker stays hidden while building');
    expect(markerDoc).toContain('Play-mode generation now keeps maze data creation full-stage but row-slices the visual Draw stage');
    expect(markerDoc).toContain('Browser scene proof drove the player to the goal, observed `reason: goal`, then verified play mode settled on a new seed.');
    expect(markerDoc).toContain('runtime-diagnostics-only `qa` movement bridge');
    expect(markerDoc).toContain('records per-step QA acceptance/lock reasons');
    expect(markerDoc).toContain('Live play lifecycle proof');
    expect(markerDoc).toContain('Explicit play lifecycle proof');
    expect(markerDoc).toContain('prioritizes deconstructing/handoff over staged-build residue');
    expect(markerDoc).toContain('goal-hold -> deconstructing -> handoff -> building -> ready');
    expect(markerDoc).toContain('explicitLifecyclePass = true');
    expect(markerDoc).toContain('window.__MAZER_QA__');
    expect(markerDoc).toContain('postGoalLifecycle.pass = true');
    expect(markerDoc).toContain('settledFreshSeed = true');
    expect(markerDoc).toContain('Stick-control lifecycle proof');
    expect(markerDoc).toContain('AI unseen-goal target proof');
    expect(markerDoc).toContain('short below-repeat-threshold stick drag');
    expect(markerDoc).toContain('executedMoveCount = 152');
    expect(markerDoc).toContain('noAutoTuningWithoutValidator');
    expect(markerDoc).toContain('--atlas-consumer-root');
    expect(markerDoc).toContain('screenContract.pass');
    expect(contractDoc).toContain('`targetComplexity` remains the only numeric source of truth for level and rank.');
    expect(contractDoc).toContain('Player and AI progression are separate.');
    expect(contractDoc).toContain('AI-runner performance acts as the tuning test dummy');
    expect(contractDoc).toContain('edgeWrapScore');
    expect(contractDoc).toContain('edgeWrapChoiceScore');
    expect(contractDoc).toContain('edgeWrapShortcutReliefScore');
    expect(contractDoc).toContain('edgeWrapReliefScore');
    expect(contractDoc).toContain('splitScore');
    expect(contractDoc).toContain('deadEndPressureScore');
    expect(contractDoc).toContain('weightedSplitPressureScore');
    expect(contractDoc).toContain('weightedDeadEndPressureScore');
    expect(contractDoc).toContain('routeEfficiencyPressureScore');
    expect(contractDoc).toContain('renderSafetyPenaltyScore');
    expect(contractDoc).toContain('fillQualityScore');
    expect(contractDoc).toContain('recentSignals');
    expect(contractDoc).toContain('first smoothing window records the last six signals');
    expect(contractDoc).toContain('numeric run-quality score');
    expect(contractDoc).toContain('Route waste can force an `ease` signal');
    expect(contractDoc).toContain('Unsafe frame timing forces `hold`');
    expect(contractDoc).toContain('AI completed cycles can increase while visible level/rank do not move on every single cycle');
    expect(markerDoc).toContain('searching-but-competent local-memory runs can advance skill without requiring perfect pathing');
    expect(markerDoc).toContain('deterministic multi-run calibration proof');
    expect(markerDoc).toContain('`npm run ai:calibrate -- --summary-only` now runs a maintained generated-seed calibration sample');
    expect(markerDoc).toContain('the resolved AI perception profile');
    expect(markerDoc).toContain('`--ai-rank=<E|D|C|B|A|S>` and `--ai-level=<1-99>`');
    expect(markerDoc).toContain('`npm run ai:calibrate:ranks` runs `--summary-only --rank-sweep`');
    expect(markerDoc).toContain('per-rank summaries over one shared scale/seed window');
    expect(markerDoc).toContain('comparison now separates controller route skill from progression-score movement');
    expect(markerDoc).toContain('`monotonicAverageScorePass`');
    expect(markerDoc).toContain('`monotonicRouteEfficiencyPass`');
    expect(markerDoc).toContain('route-efficiency-pressure deltas');
    expect(markerDoc).toContain('Rank defaults now use a non-degrading competent-scout floor');
    expect(markerDoc).toContain('`goalTargetLeakPass = true`, `monotonicAverageScorePass = true`, and `monotonicRouteEfficiencyPass = true`');
    expect(markerDoc).toContain('score E/D/C/B/A/S = `65 / 75.8 / 75.8 / 75.8 / 75.8 / 75.8`');
    expect(markerDoc).toContain('route pressure E/D/C/B/A/S = `63.811 / 61.679 / 61.679 / 61.679 / 61.679 / 61.679`');
    expect(markerDoc).toContain('implements explicit human bias profiles');
    expect(markerDoc).toContain('fixes the runner-plan cache so rank/level/bias settings cannot reuse a stale balanced route');
    expect(markerDoc).toContain('`npm run ai:calibrate:biases`');
    expect(markerDoc).toContain('`speedrunner` average 1.216');
    expect(markerDoc).toContain('`shortcut-gambler` average 2.963');
    expect(markerDoc).toContain('local lookahead more human-useful');
    expect(markerDoc).toContain('D establishes the first improved local-memory scout profile');
    expect(markerDoc).toContain('C/B/A/S inherit that D-grade controller floor at level 1');
    expect(markerDoc).toContain('shorter known-route cap');
    expect(markerDoc).toContain('step-counted wrong-branch telemetry no longer makes competent local-memory wandering look chaotic');
    expect(markerDoc).toContain('non-chaotic local-memory exhaustion now holds maze level');
    expect(markerDoc).toContain('`averageScore = 59.417`');
    expect(markerDoc).toContain('`endingLevel = 7`');
    expect(markerDoc).toContain('`endingRank = D`');
    expect(markerDoc).toContain('`endingTargetComplexity = 34`');
    expect(markerDoc).toContain('zero goal-target leaks plus zero invalid moves');
    expect(markerDoc).toContain('challenge/ease/hold = 20/16/24');
    expect(markerDoc).toContain('AI perception proof');
    expect(markerDoc).toContain('`lookaheadDepth = 11`');
    expect(markerDoc).toContain('`optionalRetargetLimit = 2`');
    expect(markerDoc).toContain('`wrapMentalCost = 0.54`');
    expect(markerDoc).toContain('`solvePreviewBudget = 4`');
    expect(markerDoc).toContain('advance from rank E to D without needing a perfect solver route');
    expect(markerDoc).toContain('`levelProgressPercent`');
    expect(markerDoc).toContain('`complexityUntilNextLevel`');
    expect(markerDoc).toContain('`nextLevelTargetComplexity`');
    expect(markerDoc).toContain('`skillTrend`');
    expect(markerDoc).toContain('active procedural difficulty profile');
    expect(markerDoc).toContain('level 1 as a true tutorial/simple maze');
    expect(markerDoc).toContain('tutorial, starter, explorer, navigator, architect, and mythic');
    expect(markerDoc).toContain('profile now also flows into runtime maze generation as real topology pressure');
    expect(markerDoc).toContain('| Maze complexity/path topology | 43% |');
    expect(markerDoc).toContain('separates edge-wrap scoring into `edgeWrapChoiceScore`');
    expect(markerDoc).toContain('`edgeWrapShortcutReliefScore` for wraps that make the shortest route unusually easy');
    expect(markerDoc).toContain('| Play camera zoom and minimap | 0% |');
    expect(markerDoc).toContain('changes only the camera zoom inside the maze border');
    expect(markerDoc).toContain('bottom-left minimap overlay about one-eighth the maze-border size');
    expect(markerDoc).toContain('one shared viewport contract');
    expect(markerDoc).toContain('level-1/tutorial generation suppresses shortcuts, required wraps, and perimeter feeders');
    expect(markerDoc).toContain('mythic profile pressure raises checkpoint/shortcut/reinforcement/feeders');
    expect(contractDoc).toContain('Repeated `searching but competent` receipts are allowed to raise target complexity.');
    expect(contractDoc).toContain('AI rank/level now resolve into an explicit perception profile.');
    expect(contractDoc).toContain('C/B/A/S currently inherit that D-grade level-1 controller floor');
    expect(contractDoc).toContain('shortest path still remains a post-run benchmark rather than the movement controller');
    expect(contractDoc).toContain('Progression diagnostics now expose `levelProgressPercent`, `complexityUntilNextLevel`, `nextLevelTargetComplexity`, and `skillTrend`.');
    expect(contractDoc).toContain('Progression diagnostics now also expose `generationReview`');
    expect(contractDoc).toContain('classifies the result as `under-target`, `on-target`, or `over-target`');
    expect(contractDoc).toContain('Level 1: first-clear tutorial.');
    expect(contractDoc).toContain('Perpetual loop contract:');
    expect(contractDoc).toContain('Runtime generation maps the active player/AI track into `checkpointCountMultiplier`, `shortcutCountMultiplier`, `routeQualityReinforcementMultiplier`, `requiredOppositeBorderConnections`, and `borderFeederTargetPerSide`.');
    expect(contractDoc).toContain('Difficulty delivery is intentionally measured after generation.');
    expect(contractDoc).toContain('Generation requests now carry the active player/AI target complexity into consumption.');
    expect(contractDoc).toContain('records the selected seed and delivery classification in `maze.generation.selection`');
    expect(contractDoc).toContain('`maze.generation.selection` now also records selected distance from target');
    expect(contractDoc).toContain('every sampled candidate under-delivering means the generator profile or scale pressure needs a stronger adjustment');
    expect(contractDoc).toContain('The bounded retry ladder is implemented.');
    expect(contractDoc).toContain('samples three additional seeds using a boosted pressure profile');
    expect(contractDoc).toContain('samples three more candidates with an adaptive scale/profile escalation');
    expect(contractDoc).toContain('`pressureRetryUsed`');
    expect(contractDoc).toContain('`adaptiveRetryUsed`');
    expect(contractDoc).toContain('Atlas-safe cycle telemetry reports now preserve normalized generation delivery/retry review');
    expect(contractDoc).toContain('Play-mode maze seeds are fresh per player run.');
    expect(contractDoc).toContain('An explicit `mazeSeed`/`seed` URL can pin the initial proof route');
    expect(contractDoc).toContain('Every new player maze should receive a fresh procedural seed');
    expect(contractDoc).toContain('AI Skill level/rank, run count, current time, and score');
    expect(contractDoc).toContain('Target-complexity pressure and challenge/hold/ease signals remain available in runtime diagnostics');
    expect(contractDoc).toContain('with no debug shorthand bleeding into the public skill box');
    expect(contractDoc).toContain("actorTrack: 'player' | 'ai-runner'");
    expect(contractDoc).toContain('Diagonal tiles, rooms, enemies, traps, and obstacles require one shared graph contract');
    expect(contractDoc).toContain('pressureScore');
    expect(contractDoc).toContain('optionalRetargetCount');
    expect(contractDoc).toContain('validateMazeCycleTelemetryAtlasReport(report)');
    expect(contractDoc).toContain('createMazeCycleTelemetryAtlasConsumerReceipt(report)');
    expect(contractDoc).toContain('canConsumeForTuning');
    expect(contractDoc).toContain('blocked-validation');
    expect(contractDoc).toContain('noAutoTuningWithoutValidator = true');
    expect(markerDoc).toContain('## Current Focus Order');
    expect(markerDoc).toContain('1. Procedural difficulty generator shaping plus maze topology.');
    expect(markerDoc).toContain('2. AI/playbook progression contracts.');
    expect(markerDoc).toContain('tune score/progression calibration so route-efficiency improvements show up as sane level/rank movement');
    expect(markerDoc).toContain('3. Play-mode lifecycle plus mobile UI proof.');
    expect(markerDoc).toContain('4. Account/auth/persistence hardening.');
    expect(markerDoc).toContain('5. Visual/art-system upgrade.');
    expect(markerDoc).toContain('6. Deferred graph expansion.');
  });

  test('keeps the shifting player and trail material lane tracked', () => {
    const markerDoc = readRepoFile('docs/research/MAZER_AUTH_AI_VISUAL_COMPLETION_MARKER.md');

    expect(markerDoc).toContain('| Icon-quality 2026 visual target | 5% |');
    expect(markerDoc).toContain('matching the supplied app icon');
    expect(markerDoc).toContain('data/atlas/brand/mazer/mazer-app-icon-2026-07-09-source.png');
    expect(markerDoc).toContain('| Shifting color player/trail/pulse material | 50% |');
    expect(markerDoc).toContain('| Diagonal paths and true diagonal travel | 8% |');
    expect(markerDoc).toContain('| Unified player-facing message system | 78% |');
    expect(markerDoc).toContain('not a true diagonal topology');
    expect(markerDoc).toContain('diagonal neighbor legality');
    expect(markerDoc).toContain('rainbow shifting is deliberately paused for readability');
    expect(markerDoc).toContain('pins player core, halo/accent, and all trail tiles to the green readability anchor');
    expect(markerDoc).toContain('trail pulse is pinned to the purple pulse anchor');
    expect(markerDoc).toContain('temporary green/purple lock cannot drift back to blue, pink, or yellow trail/player colors');
    expect(markerDoc).toContain('Runtime/visual diagnostics still expose compact material samples');
    expect(markerDoc).toContain('purple pulse is the only animated trail treatment');
    expect(markerDoc).toContain('capture-ui-surfaces.mjs` seeds one real QA move');
    expect(markerDoc).toContain('The played-game player and main-menu AI runner share the green anchor as a louder beacon treatment');
    expect(markerDoc).toContain('explicit advanced field commits now enter the same compact cyber message-card queue');
    expect(markerDoc).toContain('Bulk overlay field commits stay silent');
  });

  test('keeps the legacy visual one-to-one marker retired unless screenshot parity is reopened', () => {
    const retiredMarkerDoc = readRepoFile('docs/research/MAZER_LEGACY_ONE_TO_ONE_COMPLETION_MARKER.md');
    const currentTruth = readRepoFile('docs/current-truth.md');
    const agentRules = readRepoFile('AGENTS.md');

    const retiredMarker = extractRetiredMarker(retiredMarkerDoc);

    expect(retiredMarker).toBe(93);
    expect(retiredMarkerDoc).toContain('Status: retired / archival');
    expect(retiredMarkerDoc).toContain('Do not ratchet it during mechanics-first or mobile-clean work.');
    expect(currentTruth).toContain(`retired at \`${retiredMarker}%\``);
    expect(agentRules).toContain('explicitly reopened legacy screenshot 1:1 passes only');
  });
});
