import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, test } from 'vitest';

describe('UI surface capture script contract', () => {
  test('captures menu, options, play, and pause from runtime diagnostics', () => {
    const source = readFileSync(resolve(process.cwd(), 'scripts/analysis/capture-ui-surfaces.mjs'), 'utf8')
      .replace(/\r\n/g, '\n');
    const packageJson = JSON.parse(readFileSync(resolve(process.cwd(), 'package.json'), 'utf8'));

    expect(packageJson.scripts['visual:ui-surfaces']).toBe('node ./scripts/analysis/capture-ui-surfaces.mjs');
    expect(packageJson.scripts['visual:ui-transitions']).toBe('node ./scripts/analysis/capture-ui-transitions.mjs');
    expect(source).toContain("const RUNTIME_DIAGNOSTICS_ATTRIBUTE = 'data-mazer-runtime-diagnostics';");
    expect(source).toContain("const VISUAL_DIAGNOSTICS_ATTRIBUTE = 'data-mazer-visual-diagnostics';");
    expect(source).toContain('const DEFAULT_DEVICE_SCALE_FACTOR = 2;');
    expect(source).toContain('const mobileViewport = viewport.width < 720;');
    expect(source).toContain('hasTouch: transition ? false : mobileViewport');
    expect(source).toContain('isMobile: transition ? false : mobileViewport');
    expect(source).toContain("assertVisualScreenContract(screenContract);");
    expect(source).toContain('buildVisualScreenContract({');
    expect(source).toContain('const waitForVisualBuildSettled = async (page, { requireReadableTitle = false, timeoutMs = DEFAULT_TIMEOUT_MS } = {}) => {');
    expect(source).toContain('requireReadableTitle = false');
    expect(source).toContain('visual?.title?.visible === true && visual?.title?.progressPercent >= 95');
    expect(source).toContain("drawStage?.complete === true || drawStage?.lifecyclePhase === 'settled'");
    expect(source).toContain('const waitForAuthenticatedFixtureReady = async (page, { timeoutMs = DEFAULT_TIMEOUT_MS } = {}) => {');
    expect(source).toContain("runtime?.auth?.status === 'authenticated'");
    expect(source).toContain("labels.has('Start')");
    expect(source).toContain("if (authFixture === 'authenticated') {");
    expect(source).toContain('await waitForAuthenticatedFixtureReady(page, { timeoutMs });');
    expect(source).toContain('expectedOverlay: overlay');
    expect(source).toContain('return visual?.runtime?.mode === expectedMode && visual?.runtime?.overlay === expectedOverlay;');
    expect(source).toContain('screenContract: optionsSurface.screenContract');
    expect(source).toContain('const resolveRouteWithParams = (route, params) => {');
    expect(source).toContain('const isAuthGatedMenuSurface = (surface) => (');
    expect(source).toContain("hasTextLabels(surface, ['Login'])");
    expect(source).toContain('const OPTIONS_BASE_EXPECTED_LABELS = Object.freeze([');
    expect(source).toContain('const resolveOptionsExpectedLabels = (authenticated) => [');
    expect(source).toContain("authenticated ? 'Log out' : 'Account'");
    expect(source).toContain("authFixture === 'authenticated' || menu.diagnostics.runtime?.auth?.status === 'authenticated'");
    expect(source).toContain("surfaces.menu.authStatus === 'authenticated' || hasTextLabels(surfaces.options, ['Log out'])");
    expect(source).toContain('const getVisualButtonPoint = (visual, text) => {');
    expect(source).toContain("const button = (visual?.buttons ?? []).find((entry) => entry?.text === text && isFiniteBounds(entry?.bounds));");
    expect(source).toContain("login: getVisualButtonPoint(visual, 'Login') ?? {");
    expect(source).toContain("start: getVisualButtonPoint(visual, 'Start') ?? {");
    expect(source).toContain("options: getVisualButtonPoint(visual, 'Options') ?? {");
    expect(source).toContain('const openOptionsOverlayFromMenu = async (page, point, expectedLabels, timeoutMs) => {');
    expect(source).toContain("await clickPoint(page, point, 'Options');");
    expect(source).toContain('await page.touchscreen.tap(point.x, point.y);');
    expect(source).toContain('timeoutMs: Math.min(timeoutMs, 10_000)');
    expect(source).toContain('const openOptionsOverlayViaQa = async (page, timeoutMs) => {');
    expect(source).toContain('window.__MAZER_QA__?.openOptionsOverlay');
    expect(source).toContain('api.openOptionsOverlay()');
    expect(source).toContain('Unable to open Options overlay through QA bridge');
    expect(source).toContain('const PLAY_TRAIL_SEED_MOVES = Object.freeze([');
    expect(source).toContain('const seedPlayTrailForVisualProof = async (page, { timeoutMs = DEFAULT_TIMEOUT_MS } = {}) => {');
    expect(source).toContain('window.__MAZER_QA__?.movePlayPlayer');
    expect(source).toContain('visual?.markerStyle?.trailPulseEnabled === true');
    expect(source).toContain('Unable to seed play trail for visual proof');
    expect(source).toContain("id: '01-menu'");
    expect(source).toContain("id: '02-auth'");
    expect(source).toContain("id: '02-options'");
    expect(source).toContain("id: '02-options-bottom'");
    expect(source).toContain("id: '03-play'");
    expect(source).toContain("id: '04-pause'");
    expect(source).toContain("id: '04-pause-bottom'");
    expect(source).toContain("mode: 'menu'");
    expect(source).toContain("mode: 'play'");
    expect(source).toContain("overlay: 'none'");
    expect(source).toContain("overlay: 'options'");
    expect(source).toContain("overlay: 'auth'");
    expect(source).toContain("overlay: 'pause'");
    expect(source).toContain('expectedLabels: []');
    expect(source).toContain("reason: 'auth-gated-menu'");
    expect(source).toContain("const playRoute = authGatedMenu ? resolveRouteWithParams(route, { mode: 'play', overlay: null }) : route;");
    expect(source).toContain('const playTrailSeed = await seedPlayTrailForVisualProof(page, { timeoutMs });');
    expect(source).toContain('const latestMenuDiagnostics = await readDiagnostics(page);');
    expect(source).toContain('const latestMenuButtons = getMenuButtonPoints(latestMenuDiagnostics.visual);');
    expect(source).toContain("expectedLabels: ['PAUSE']");
    expect(source).toContain("expectedLabels: ['Paused', 'PLAYER GUIDE', 'Reset', 'Menu']");
    expect(source).toContain("url.searchParams.set('mazeSeed', mazeSeed);");
    expect(source).toContain("url.searchParams.set('authFixture', authFixture);");
    expect(source).not.toContain("url.searchParams.set('pathStyle', pathStyle);");
    expect(source).toContain('expected=corridor');
    expect(source).toContain('const checks = buildSurfaceChecks({');
    expect(source).toContain('const isIgnorableConsoleMessage = (message) => (');
    expect(source).toContain("message.text.includes('WebGL: CONTEXT_LOST_WEBGL')");
    expect(source).toContain("createCheck(\n      'play-player-green'");
    expect(source).toContain("createCheck(\n      'play-goal-red'");
    expect(source).toContain("createCheck(\n      'play-stick-controls'");
    expect(source).toContain("createCheck(\n      'play-trail-pulse-seeded-on'");
    expect(source).toContain('deviceScaleFactor,');
    expect(source).toContain('authFixture: authFixture ?? null');
    expect(source).toContain('playTrailSeed,');
    expect(source).toContain("createCheck(\n      'menu-text-labels'");
    expect(source).toContain("createCheck(\n      'menu-title-readable'");
    expect(source).toContain("createCheck(\n      'auth-surface'");
    expect(source).toContain("createCheck(\n      'auth-text-labels'");
    expect(source).toContain("hasLabels(surfaces.auth, ['Account', 'Login', 'Create Account', 'Reset Password'])");
    expect(source).toContain('const collectTextBoundsIssues = (surfaceId, surface, viewport) => {');
    expect(source).toContain('const collectNativeInputBoundsIssues = (surfaceId, surface, viewport) => {');
    expect(source).toContain('const collectTextOverlapIssues = (surfaceId, surface) => {');
    expect(source).toContain('const collectMenuControlSpacingIssues = (surface) => {');
    expect(source).toContain("createCheck(\n      'mobile-text-label-bounds'");
    expect(source).toContain("createCheck(\n      'mobile-native-input-bounds'");
    expect(source).toContain("createCheck(\n      'mobile-text-overlap'");
    expect(source).toContain("createCheck(\n      'mobile-control-spacing'");
    expect(source).toContain("createCheck(\n      'mobile-badge-text-fit'");
    expect(source).toContain('const collectOverlayScrollAffordanceIssues = (surfaceId, surface) => {');
    expect(source).toContain("createCheck(\n      'mobile-overlay-scroll-affordance'");
    expect(source).toContain("createCheck(\n      'mobile-overlay-scroll-reachability'");
    expect(source).toContain('const scrollOverlayToBottom = async (page, { timeoutMs = DEFAULT_TIMEOUT_MS } = {}) => {');
    expect(source).toContain('const desktopViewport = (before.visual?.viewport?.width ?? 0) >= 720;');
    expect(source).toContain('const wheelDelta = Math.max(scroll.maxOffset * 4, dragDistance);');
    expect(source).toContain('await page.mouse.wheel(0, wheelDelta);');
    expect(source).toContain("expectedLabels: ['Controls']");
    expect(source).toContain("expectedLabels: ['Move Speed', 'Reset Progress', 'Reset', 'Menu']");
    expect(source).toContain('optionsSurface.diagnostics.visual?.overlayUi');
    expect(source).toContain('pause.diagnostics.visual?.overlayUi');
    expect(source).toContain("nativeInputs: authSurface.nativeInputs");
    expect(source).toContain('progressionBadge: menu.diagnostics.visual?.progressionBadge');
    expect(source).toContain('title: menu.diagnostics.visual?.title');
    expect(source).toContain('progressionBadge: authSurface.diagnostics.visual?.progressionBadge');
    expect(source).toContain('progressionBadge: play.diagnostics.visual?.progressionBadge');
    expect(source).toContain('all active text labels stay inside viewport');
    expect(source).toContain('visible progression badges fit their chrome');
    expect(source).toContain("deviceScaleFactor: parseIntegerArg(args['device-scale-factor'], DEFAULT_DEVICE_SCALE_FACTOR)");
    expect(source).toContain("authFixture: typeof args['auth-fixture'] === 'string' ? args['auth-fixture'] : undefined");
    expect(source).toContain("authFixture: result.authFixture");
    expect(source).not.toContain("expectedLabels: ['Exit', 'Start', 'Options']");
    expect(source).toContain("authGated ? hasLabels(surfaces.menu, ['Login']) : hasLabels(surfaces.menu, ['Start', 'Options'])");
    expect(source).toContain("authGated\n        ? surfaces.options.skipped === true");
    expect(source).toContain('const optionsCaptureExpectedLabels = [...OPTIONS_BASE_EXPECTED_LABELS];');
    expect(source).toContain('await openOptionsOverlayFromMenu(page, latestMenuButtons.options, optionsCaptureExpectedLabels, timeoutMs);');
    expect(source).toContain("if (authFixture === 'authenticated') {");
    expect(source).toContain('skipWait = false');
    expect(source).toContain('skipWait ? await readDiagnostics(page)');
    expect(source).toContain('return expected.every((label) => currentLabels.has(label));');
    expect(source).toContain('Surface ${id} missing labels after direct diagnostics read');
    expect(source).toContain('await openOptionsOverlayViaQa(page, timeoutMs);');
    expect(source).toContain("skipWait: authFixture === 'authenticated'");
    expect(source).toContain('expectedLabels: optionsCaptureExpectedLabels');
    expect(source).toContain('hasLabels(surfaces.options, optionsExpectedLabels)');
    expect(source).toContain("!hasLabels(surfaces.options, ['Game Toggles', 'Maze Scale', 'Camera Scale'])");
    expect(source).toContain("hasLabels(surfaces.play, ['PAUSE']) && !hasLabels(surfaces.play, ['RESET'])");
    expect(source).toContain("hasLabels(surfaces.pause, ['Paused', 'PLAYER GUIDE', 'Reset', 'Menu'])");
    expect(source).toContain("!hasLabels(surfaces.pause, ['Game Toggles', 'Account', 'Resume'])");
    expect(source).toContain('const reportPath = resolve(outputDir, \'report.md\');');
    expect(source).toContain('![Menu](${summary.screenshots.menu})');
    expect(source).toContain('![Auth](${summary.screenshots.auth})');
    expect(source).toContain('const DEFAULT_TRANSITION_VIEWPORTS = Object.freeze({');
    expect(source).toContain('const captureViewportTransition = async ({');
    expect(source).toContain('const stableBoardDiagnostics = (board) => board ? {');
    expect(source).toContain('await page.setViewportSize(viewport);');
    expect(source).toContain('restoredDiagnosticsMatch: JSON.stringify(initial.diagnostics) === JSON.stringify(restored.diagnostics)');
    expect(source).toContain('nativeInputs: surface.nativeInputs');
    expect(source).toContain('const buildViewportTransitionChecks = (transitions) =>');
    expect(source).toContain('checks.push(...buildViewportTransitionChecks(transitions));');
  });
});
